EverywhereNews/Models/ApiResponse.cs
using EverywhereNews.Constants;

namespace EverywhereNews.Models;

public class ApiResponse
{
        public String Status { get; set; }
        public ErrorCodes? Code { get; set; }
        public string Message { get; set; }
        public List<Article>? Articles { get; set; }
        public int TotalResults { get; set; }
}

EverywhereNews/Models/Article.cs
namespace EverywhereNews.Models;

public class Article
{
    public Source Source { get; set; }
    public string Author { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Url { get; set; }
    public string UrlToImage { get; set; }
    public DateTime? PublishedAt { get; set; }
}

EverywhereNews/Models/ErrorViewModel.cs
namespace EverywhereNews.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EverywhereNews/Models/SearchFormModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EverywhereNews.Models;

public class SearchFormModel
{
    public required SelectList Countries { get; set; }
    public string? Search { get; set; }
    public string? Country { get; set; }
    public required SelectList Categories { get; set; }
    public string? Category { get; set; }
    public required SelectList Languages { get; set; }
    public string? Language { get; set; }
 
}

EverywhereNews/Models/Source.cs
namespace EverywhereNews.Models;

public class Source
{
    public string Id { get; set; }
    public string Name { get; set; }
}

EverywhereNews/Components/SearchFormViewComponent.cs
using EverywhereNews.Constants;
using EverywhereNews.Models;
using Microsoft.AspNetCore.Mvc;

namespace EverywhereNews.Components;

public class SearchFormViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(string selectedCountry,string selectedCategory, string selectedLanguage)
    {
        var searchFormModel = new SearchFormModel
        {
            Countries = Countries.CountrySelectList(selectedCountry),
            Categories = Categories.CategorySelectList(selectedCategory),
            Languages = Languages.LanguageSelectList(selectedLanguage)
        };
        return await Task.FromResult(View(searchFormModel));
    }
}

EverywhereNews/Controllers/HomeController.cs
using EverywhereNews.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using EverywhereNews.Services;

namespace EverywhereNews.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly INewsClient _newsClient;
        public string Country { get; set; } = "us";
        public string Category { get; set; } = "all";
        public string Language { get; set; } = "all";
        public string Search { get; set; } = string.Empty;
        public string Source { get; set; } = "top";
        public HomeController(ILogger<HomeController> logger, INewsClient newsClient)
        {
            _logger = logger;
            _newsClient = newsClient;
        }

        public async Task<IActionResult> Index(string? source, string? country,string?category, string?language, string? search)
        {
            Search = search ?? string.Empty;
            Country = country ?? "us";
            Category = category ?? "all";
            Language = language ?? "all";
            Source = source??"top";
            ViewBag.Search = Search;
            ViewBag.SelectedCountry = Country;
            ViewBag.SelectedCategory = Category;
            ViewBag.SelectedLanguage = Language;
            ViewBag.Source = Source;
            ViewBag.NewsTitle = "News Everywhere";
            IEnumerable<Article>? articles;
            if (Source =="top")
            {
                articles = await _newsClient.GetTopHeadlines(Country,Search,Category);
            }
            else
            {
                articles = await _newsClient.GetEverything(Search,Language);
            }

            return View(articles);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EverywhereNews/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<EverywhereNews.Models.Article>

<div class="text-center">
    <h1 class="display-4">@ViewBag.NewsTitle</h1>
    <p>Uncover the World: News Everywhere - Your Gateway to Global Insights!</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            @await Component.InvokeAsync("SearchForm", new
                {
                    selectedCountry = ViewBag.SelectedCountry,
                    selectedCategory = ViewBag.SelectedCategory,
                    selectedLanguage = ViewBag.SelectedLanguage,
                })
        </div>
    </div>
    <div class="row">
        @foreach (var news in Model)
        {
            <div class="col-6">
                <div class="card">
                    @if (news?.UrlToImage != null)
                    {
                        <img src="@news.UrlToImage" class="card-img-top" alt="...">
                    }
                    else
                    {
                        <img src="~/images/news.png" class="card-img-top" alt="...">
                    }
                    <div class="card-body">
                        <h5 class="card-title">@news.Title</h5>
                        <p class="card-text">@news.Description</p>
                        <p class="card-text"><small class="text-body-secondary align-content-end">Published by :@news.Author @@ @news.PublishedAt</small></p>
                        <a href="@news.Url" target="_blank" class="card-link">more details...</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {

<script>
        $(document).ready(function () {
            let source = '@ViewBag.Source';
            if (source === 'top') {
                $("#rdoTopHeadlines").prop('checked', true);
                $("#language").prop('disabled', true);
                $("#search").removeProp('required');
            } else {
                $("#rdoEverywhere").prop('checked', true);
                $("#language").prop('disabled', false);
                $("#search").addProp('required');
            }
            handleSourceOption();
           
        });
        function handleSourceOption() {
            $("[name=source]").change(function () {
                console.log($(this).val());
                if ($(this).val() === 'top') {
                    $("#language").prop('disabled', true);
                    $("#country").prop('disabled', false);
                    $("#category").prop('disabled', false);
                    $("#search").prop('required',false);
                } else {
                    $("#language").prop('disabled', false);
                    $("#country").prop('disabled', true);
                    $("#category").prop('disabled', true);
                    $("#search").prop('required',true);
                }
            });
        }
        
</script>
}

EverywhereNews/Views/Shared/Components/SearchForm/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SearchFormModel
@{
}
<form method="post" class="row g-3" asp-controller="Home" asp-action="Index">
    <div class=" mb-2 text-center">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" checked name="source" id="rdoTopHeadlines" value="top">
            <label class="form-check-label" for="rdoTopHeadlines">Top Headlines</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="source" id="rdoEverywhere" value="everywhere">
            <label class="form-check-label" for="rdoEverywhere">Everywhere</label>
        </div>
    </div>
    <div class="col-md-6">
        <label for="country" class="form-label">Country</label>
        <div class="input-group ">
            <select class="form-select" asp-items="@Model.Countries" name="country" id="country">
            </select>
        </div>
    </div>
    <div class="col-md-4">
        <label for="category" class="form-label">Category</label>
        <div class="input-group ">
            <select class="form-select" asp-items="@Model.Categories" name="category" id="category">
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <label for="language" class="form-label">Language</label>
        <div class="input-group ">
            <select class="form-select" asp-items="@Model.Languages" name="language" id="language">
            </select>
        </div>
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" id="search" placeholder="Search for news" name="search" value="@ViewBag.search">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">🔍 Search</button>
    </div>
</form>

EverywhereNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EverywhereNews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EverywhereNews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EverywhereNews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EverywhereNews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>